### PR TITLE
Merge latest bugfixes and improvements from master to docker

### PR DESCRIPTION
**Pull request by lubocode**
This will take some time since a lot has to be resolved manually and cannot simply be taken over from master.
The peculiarities of the docker branch shall be documented in a README in the root of the docker branch.

The go version has priority, as the python docker version is not yet finished anyway.

READMEs should not be taken from master, as they are not for display on github, but for the description on dockerhub.

The script will continue to use screen instead of systemctl since setting that up in a docker does not have any major benefits over screen and just introduces complexity.

### CODE REVIEW

**Comment by lubocode** [comment]
image

Well, shit.
Guess I'll have to look into resolving conflicts on my PC.
Should only delay by a little bit, though.

**Comment by gekigek99** [comment]
> The go version has priority, as the python docker version is not yet finished anyway.
> 
> The script will continue to use screen instead of systemctl since setting that up in a docker does not have any major benefits over screen and just introduces complexity.

ok completely agree... (i'm not really sure what to do for the screen command, i would like to keep it in the master for easy use of users but at the same time it's a pain for me to remember to replace it every time... plus the systemctl it's kinda cleaner ahah)

**Comment by gekigek99** [comment]
> 
> 
> image
> 
> Well, shit.
> Guess I'll have to look into resolving conflicts on my PC.
> Should only delay by a little bit, though.

maybe you can resolve it with the GitHub Desktop app... i'm not sure but it's worth the time to check

**Comment by lubocode** [comment]
Finished pull request by manually adopting changes in a different commit and finalizing pull request via merging master into docker following the git instructions:
```
git checkout docker
git merge --no-ff master
git push
```

**Pull request merged**
