### PR TITLE
pull request

### PR DESCRIPTION
**Pull request by gekigek99**
Hi I've read the great job you have done!!!
Are you planning on pulling a request to my rep?

### CODE REVIEW

**Comment by gekigek99** [comment]
Now that I am thinking about it we could create a branch from my repository to keep all these related codes in just one place for people to easily find everything.
Plus all the credits are given to the creator of the code in this way.
what do you think?

**Comment by gekigek99** [comment]
@lubocode If you need I can make you a collaborator so that you can work on your branch.
tell me what you think

**Comment by lubocode** [comment]
> @lubocode If you need I can make you a collaborator so that you can work on your branch.
> tell me what you think

@gekigek99 Sounds good to me.
My original purpose was to build a Docker image for myself, but with the code diverging this much, it might be best for importing all improvements into the image, since other people started using it as well.

Right now I have a lot of work to do for university, but from next week on the amount of work I have to do will be reduced and I can try merging both versions on a branch in your repo.

**Comment by lubocode** [comment]
The python version of the Dockerfile is largely untested by the way, since I wanted to get the go version working, before my new uni semester started.
In its current state it has some problems, because copying into a volume with the Dockerfile instructions is somewhat finicky.

**Comment by gekigek99** [comment]
yea sure I completely understand I also have a lot due for university but no pressure there is no deadline ahahah
I'll make you a collaborator so you can create your own branch.

**Comment by gekigek99** [comment]
ok I have sent you the request.
Since I am not extremely familiar with github tell me if you can create a branch and modify its content

**Comment by lubocode** [comment]
I have created a branch and will make a pull request from my fork to that branch, to resolve conflicts.
For trying stuff out, I will still keep my fork open.
I will also redirect my Dockerhub image build to the new branch.

For now, I am going to close this pull request and handle merging into the docker branch either on the weekend or next week.

**Pull request closed without merging**
