### PR TITLE
pull request

### PR DESCRIPTION
**Pull request by gekigek99**
Hello I've seen the great job you have done!!!
Do you plan on pulling it on my rep?

### CODE REVIEW

**Comment by gekigek99** [comment]
Ok in the next days I'll review more deeply your comitts.
I'll let you know.
thanks

**Comment by gekigek99** [comment]
I actually think that creating a branch would be a great idea so we don't mix our work while using 1 repository for people to look into

**Comment by gekigek99** [comment]
@dangercrow If you need I can make you a collaborator so that you can work on your branch.
tell me what you think

**Comment by dangercrow** [comment]
Yeah sure, happy to get it pulled back into upstream.

I've yet to test this, just been playing around with it. 

Note the main motivation of this PR was #10 - I just decided to refactor the whole thing whilst I was here, because why not :P

**Comment by dangercrow** [comment]
As a side note, I don't entirely agree this should be kept branched - I think it should be on master, or in a fork.
After all, master gets maintained, branches, in general, don't.
Whereas forks are the owners responsibility.
i.e. I will be responsible for looking after my fork, but who looks after "my" branch on this repo?
So, I think it's probably best to get the PRs (and this applies to #12 too) into master

**Comment by gekigek99** [comment]
okok I understand.
the only problem is that I didn't want to loose my work since i think it can still benefit the boy that doesn't know how it works and seeing just one file can help him set up everything.

Maybe you could create and push a folder dedicated to you with the changes you make so that we can continue to work on the more professional code and still leave some traces for people to just download a file and set it working in 2 sec.

In any case in next days I'll see more in depth your code thanks

**Pull request closed without merging**
